[wip] show notifications for start, stop and delete actions from the tray menu
crc-org/tray-electron pull request #10
Opened 2021-09-15 08:19 UTC by anjannath

since we'll be removing the `Error` and `Success` structs, `/stop`, `/delete` would not return a body on success, so we need to make changes in the commander to get this result.

2021-09-15 11:37 UTC, gbraad approved these changes

2021-09-16 06:12 UTC, gbraad commented
Please use a spellchecker for text strings.

2021-09-16 06:12 UTC, gbraad commented on main.js
> +  showNotification("Deleteing", "CodeReady Container cluster is being deleted")
`s/Deleteing/Deleting/`

2021-09-16 06:19 UTC, gbraad requested changes
Do we need to add `app.setAppUserModelId("CodeReady Containers");` ?

https://docs.microsoft.com/en-us/windows/win32/shell/appids#how-to-form-an-application-defined-appusermodelid

Perhaps I see the issue because of https://github.com/electron/electron/issues/7934#issuecomment-260078298

2021-09-17 07:01 UTC, anjannath commented
> Do we need to add app.setAppUserModelId("CodeReady Containers"); ?

> https://docs.microsoft.com/en-us/windows/win32/shell/appids#how-to-form-an-application-defined-appusermodelid

According to the [section](https://docs.microsoft.com/en-us/windows/win32/shell/appids#how-to-form-an-application-defined-appusermodelid) about ID from the above link it should be `redHat.CodeReadyContainers` or `redHat.CodeReadyContainers.Tray`.

2021-09-17 07:02 UTC, anjannath commented
@gbraad The start, stop and delete calls are now using the async, await pattern to handle the errors from the api side. PTALA

2021-09-17 07:08 UTC, gbraad commented
> `redHat.CodeReadyContainers.Tray`

Also concluded this. but this needs to be recorded as part of the install to map the appmodel id against a known application name, eg. "CodeReady Containers". Just this match/record is not performed now. It seems Zettlr has the same issue and also no known solution as of yet.

2021-09-17 07:10 UTC, gbraad commented on main.js
> +      showNotification("Cluster started", "CodeReady Containers cluster has successfully started");
'has' => 'has been' or no 'has' at all?

2021-09-17 07:10 UTC, gbraad commented on main.js
> +    showNotification("Cluster Deleted", "CodeReady Containers cluster is successfully deleted");
"is" => ditto, don't use a different form or verb

2021-09-17 07:11 UTC, gbraad commented on main.js
> +    showNotification("Cluster Stopped", "CodeReady Containers cluster has stopped")
@robin-owen what would you say. Does this sound OK?

2021-10-18 08:00 UTC, anjannath commented
@gbraad I updated the sentences to what we currently have on the native tray

2021-11-01 05:50 UTC, gbraad commented
Please separate commits according to what is added.
This PR also contains two very different things.

This makes it harder to identify issues and do a review.

2021-11-01 07:45 UTC, anjannath commented
> 
> 
> Please separate commits according to what is added. This PR also contains two very different things.
> 
> This makes it harder to identify issues and do a review.

The second commit about AppID is a small enough change and is related to notifications, as this is needed to show well formed toas notifications. so kept them in a single PR

Another part for displaying the notification is to add the same appID to the shortcut of the tray exe, which should be handled during installation

2021-12-08 13:05 UTC, gbraad commented
@anjannath Does this need to be be added?

2021-12-08 15:34 UTC, anjannath commented
@gbraad I need to have another look here, will fix merge conflicts and update

2021-12-17 11:38 UTC, anjannath commented
Closing as most of the code is unusable now after the refactors and addition of react
Will file a new one

2021-12-17 11:38 UTC, closed without merging