Fixes #90 add developer terminal for macOS
crc-org/tray-electron pull request #104
Opened 2022-01-21 12:44 UTC by anjannath

2022-01-21 12:54 UTC, anjannath commented
@praveenkumar can you please try this on macOS

2022-01-24 06:56 UTC, gbraad commented
^^^ @praveenkumar I'd appreciate feedback

2022-01-24 09:43 UTC, gbraad commented on main.js
>        body: "Only supported on Windows currently"
Please update this line.

2022-01-24 09:44 UTC, gbraad requested changes
Contains a "WIndows only" remark

2022-01-25 04:55 UTC, anjannath commented on main.js
>        body: "Only supported on Windows currently"
done

2022-01-25 06:45 UTC, gbraad approved these changes

2022-01-25 06:45 UTC, merged