[wip] Add window to set pull secret
crc-org/tray-electron pull request #11
Opened 2021-10-12 11:58 UTC by anjannath

This adds a pull secret window which can be opened from the settings window to set a pull secret

2021-11-01 05:45 UTC, gbraad commented on main.js
> +  BrowserWindow.getFocusedWindow().close();
why is this needed?

2021-11-01 05:47 UTC, gbraad requested changes

2021-11-01 05:47 UTC, gbraad commented on pullsecret.js
> +        ipcRenderer.send('close-focused')
... to allow the pull-secret window to close itself?

this can't be:
```js
       var window = remote.getCurrentWindow();
       window.close();
```

2021-11-01 06:00 UTC, anjannath commented on pullsecret.js
> +        ipcRenderer.send('close-focused')
yes, it can be.. but remote will be deprecated soon, so used the ipc mechanism above

2021-11-03 06:09 UTC, gbraad commented on pullsecret.js
> +        ipcRenderer.send('close-focused')
^^^ soon? It would take effort to handle overall.
And rather see that as a one-time overhaul... 
... more likely the first phase would be to use: https://github.com/electron/remote

2021-12-16 17:17 UTC, gbraad commented
Part of the code will be used, but a new stage will be added to the wizard to deal with this.

2021-12-16 17:17 UTC, closed without merging