Add minimal welcome screen
crc-org/tray-electron pull request #12
Opened 2021-10-18 12:09 UTC by anjannath

2021-10-18 12:37 UTC, gbraad commented
~~Can we open an associated issue to track what we actually want to do?~~ See #13

2021-10-27 05:47 UTC, gbraad reviewed
Can you extract the CircleCI build as a separate PR?

2021-10-27 05:59 UTC, anjannath commented
@gbraad Done, PR with circleci commit is #15

2021-11-01 05:27 UTC, gbraad reviewed
Also, the commit "set the ocp icon as app icon for release build" should not be part of this PR

2021-11-01 05:29 UTC, gbraad commented on index.css
> +    display: none;
not sure if this a default.

you might wanna solve this with a class such as `.tab #hidden` and `.tab #shown` instead. This means the display is toggled with adding/removing the class.

2021-11-01 05:31 UTC, gbraad commented on welcome.js
> +      document.getElementById("prev-button").style.display = "none";
... which in that case would not have to toggle the style of a single attribute

2021-11-01 05:33 UTC, gbraad commented on welcome.js
> +        nextPrev(1)
explicit `showNext();` and `showPrev()` are preferred.
What if I specify `(-2)`. Would that work? Yes... but what does it mean? You shouldn't have to count and remember the IDs of the tabs.

2021-11-01 05:35 UTC, gbraad commented on welcome.js
> +showTab(currentTab)
These two lines are better named as a functio

`showFromStart()`. the knowledge of id=0 and showtab(id) is very specific.

2021-11-01 05:36 UTC, gbraad requested changes
See comments.

2021-11-01 06:06 UTC, anjannath commented
> Also, the commit "set the ocp icon as app icon for release build" should not be part of this PR

Yeah, will take out this commit and submit as separate PR

2021-11-03 06:25 UTC, gbraad commented on welcome.html
> +    <div class="tab">
For example:
```html
  <div id="tabs>
    <div class="tab shown"></div>
    <div class="tab hidden"></div>
    <div class="tab hidden"></div>
    <div class="tab hidden"></div>
  </div>
```

2021-11-03 06:31 UTC, gbraad commented on welcome.html
> +      <div class="selection-summary">
`summary` would suffice I guess.

2021-11-03 06:41 UTC, gbraad commented on welcome.html
> +    <div style="overflow:auto;">
this can be using

```
<div class="tab-footer">
  <div class="buttons">
  </div>
</div>
```

and styled in css with 

```
#tabs .tab .tab-footer {
   overflow: auto;
}

#tabs .tab .tab-footer .buttons {
   float: right;
}
```

2021-11-03 07:20 UTC, gbraad requested changes
Please, avoid in-line styling when possible

Adding id and class to elements makes styling this a lot easier.

2021-12-02 07:35 UTC, anjannath commented
closed in favor of #19

2021-12-02 07:35 UTC, closed without merging