Add about window
crc-org/tray-electron pull request #131
Opened 2022-02-03 10:35 UTC by evidolob

This PR add new command `About` in trey context menu:
<img width="182" alt="Screenshot 2022-02-03 at 12 29 37" src="https://user-images.githubusercontent.com/929743/152325406-7338abda-b4f9-497c-957c-a3b9becfec9b.png">

The `About` window on mac:
<img width="603" alt="Screenshot 2022-02-03 at 12 30 29" src="https://user-images.githubusercontent.com/929743/152325549-106e8493-9966-419e-a43d-3d88f60b3ff1.png">

On Win:

Also this PR add implemented with TypeScript, it brings `tsconfig.json` and some `*.d.ts` files with types.

Tray version taken from `app.getVersion()`, electron take it from `package.json` of app, so we need to update it during release

Also I  not sure about `bundle` version, for now I use `OpenShiftVersion` value witch return by `/version` daemon call.

2022-02-04 06:15 UTC, anjannath commented on main.js
> +let aboutWindow = undefined;
We also need to also destroy this window in the `quitApp()` function https://github.com/code-ready/tray-electron/blob/9cf6b7e91d59407a2c5878047133ea7ad0ef6d4b/main.js#L488

Without it am not able to exit the tray, and other exceptions are thrown when trying to do that

2022-02-04 06:16 UTC, anjannath commented on preload-main.js
> +    return ipcRenderer.invoke('get-about');
nice, with `invoke` values can be returned, till now we were only using `send` and `reply`

2022-02-04 06:17 UTC, anjannath commented
Tested and working as expected, apart from https://github.com/code-ready/tray-electron/pull/131#discussion_r799192048 LGTM

2022-02-04 06:57 UTC, gbraad commented
Be aware that we also have a Podman version. However, that is dependent on the 'version' + 'preset' value. This is done in the `MiniStatus` windows for example.

2022-02-04 07:01 UTC, gbraad requested changes

2022-02-04 07:01 UTC, gbraad commented on main.js
> +    ocpBundleVersion: version.OpenshiftVersion
What about the situation when the podman preset is chosen? In that case the version is not the OCP version.
That was the problem I referred to in: https://github.com/code-ready/tray-electron/issues/125#issuecomment-1026648201

2022-02-04 07:01 UTC, gbraad commented on frontend/src/global.d.ts
> +  ocpBundleVersion?: string;
this is the bundle version for when the preset is `openshift`.

2022-02-04 07:01 UTC, gbraad commented on frontend/src/components/about/AboutWindow.tsx
> +            <span className={styles.alignRight}>{this.state.ocpBundleVersion}</span>
There is also a `podmanVersion`.

2022-02-04 07:05 UTC, gbraad commented
Also make sure to link the issue: `Fixes #...` in the first comment and git description.

2022-02-04 11:46 UTC, gbraad commented on frontend/src/components/about/AboutWindow.tsx
> +              <Button variant="link" className={styles.docButton} icon={<ExternalLinkSquareAltIcon />} iconPosition="right" component="a" href='https://access.redhat.com/documentation/en-us/red_hat_c
This should link to the version documentation, but this link is only based on the first two of the version: major, minor.

2022-02-04 11:50 UTC, gbraad commented on frontend/tsconfig.json
> +  "compilerOptions": {
Can this be a separate commit to add TypeScript support. #129

2022-02-04 11:51 UTC, gbraad commented on main.js
> +// About
Any ideas how to improve on this?

2022-02-04 11:55 UTC, gbraad commented on main.js
> +    title: 'About',
Yeah, first to do #89

2022-02-04 12:02 UTC, gbraad commented on main.js
> +    if (url.startsWith('https:')) {
Please use https://github.com/code-ready/tray-electron/blob/9cf6b7e91d59407a2c5878047133ea7ad0ef6d4b/main.js#L582

2022-02-04 12:14 UTC, gbraad commented on frontend/package.json
> +    "@types/jest": "^27.4.0",
These are needed for typescript, right?

2022-02-04 12:15 UTC, gbraad commented on frontend/src/components/about/AboutWindow.tsx
> +import logo from "../../assets/crc-logo-black.png";
Can we move assets like logo and css together at the end?

2022-02-04 12:16 UTC, gbraad commented on frontend/src/components/about/AboutWindow.tsx
> +    window.document.title = "About";
Didn't the window creation not already set this?
We need to update all windows as part of #89

2022-02-04 12:18 UTC, gbraad commented on frontend/src/components/about/AboutWindow.tsx
> +          <img alt="logo" src={logo} width="480" />
Maybe add the width and the actual logo url as part of the css?
In that case the size and image only need a style here.

2022-02-04 14:53 UTC, evidolob commented on frontend/tsconfig.json
> +  "compilerOptions": {
In such case I need to remove TS code comply and introduce TS with separate PR

2022-02-04 14:54 UTC, evidolob commented on main.js
> +// About
I think we need to split `main.js` in to several files, maybe under `src` directory

2022-02-04 14:55 UTC, evidolob commented on main.js
> +    title: 'About',
We also need to remove `<title>` tag from `index.html`, as `title` will be ignored if `<title>` is set.

2022-02-04 14:57 UTC, evidolob commented on frontend/package.json
> +    "@types/jest": "^27.4.0",
Yes, it only type definition for `jest` test library. I can remove that, it seems we don’t have any tests right now

2022-02-04 15:43 UTC, gbraad commented on frontend/package.json
> +    "@types/jest": "^27.4.0",
not yet...
... we will add at some point.

2022-02-04 15:45 UTC, gbraad commented on frontend/src/components/about/AboutWindow.module.scss
> +  font-weight: bold;
it almost feels in the images if the `.alignRight` also has a `font-weight: bold` assigned. 
Can't check right now.

2022-02-04 15:46 UTC, gbraad commented on frontend/src/global.d.ts
> +      // TODO: add rest of the API
eeh... ;-)

2022-02-04 15:47 UTC, gbraad commented on frontend/tsconfig.json
> +  "compilerOptions": {
You can add a first commit that deals with this, and we just move from there with this PR.

2022-02-04 15:49 UTC, gbraad commented on main.js
> +// About
I would prefer to do so. This can be easier to deal with `onboarding`, `configuration`, etc.
Perhaps create an issue to track this.

2022-02-07 07:33 UTC, evidolob commented on frontend/tsconfig.json
> +  "compilerOptions": {
Hm, I think it would be better if I add TS with separate PR, where I can do all things, including https://github.com/code-ready/tray-electron/pull/131#discussion_r799583239

2022-02-07 08:23 UTC, evidolob commented on frontend/src/components/about/AboutWindow.tsx
> +    window.document.title = "About";
No, see https://github.com/code-ready/tray-electron/pull/131#discussion_r799536933

2022-02-07 08:42 UTC, evidolob commented
@gbraad @anjannath 
I update this. Now it should show `Podman` version after https://github.com/code-ready/crc/pull/2991

Also for CRC it will show commit in version `{version}+{commit sha}` form.

Could you look again on this?

2022-02-07 11:33 UTC, gbraad commented on frontend/src/components/about/AboutWindow.module.scss
> +  font-weight: bold;
not sure if we want this

2022-02-07 11:34 UTC, gbraad commented on frontend/src/components/about/AboutWindow.tsx
> +    window.api.openLinkInDefaultBrowser(`https://access.redhat.com/documentation/en-us/red_hat_codeready_containers/${this.state.crcVersion}`);
👍 
this will make it easier to track with segment

2022-02-07 11:51 UTC, gbraad commented on main.js
> +// About
#133

2022-02-07 12:03 UTC, anjannath approved these changes

2022-02-07 12:05 UTC, anjannath commented on frontend/src/components/about/AboutWindow.tsx
> +              <Button variant="link" className={styles.docButton} icon={<ExternalLinkSquareAltIcon />} iconPosition="right" component="a" onClick={this.openDocumentationLink} target="_blank">
now since there's only one, maybe center align it? don't how it'd look, we can do it later though

2022-02-07 12:14 UTC, evidolob commented on frontend/src/components/about/AboutWindow.tsx
> +              <Button variant="link" className={styles.docButton} icon={<ExternalLinkSquareAltIcon />} iconPosition="right" component="a" onClick={this.openDocumentationLink} target="_blank">
It could look like:
<img width="603" alt="Screenshot 2022-02-07 at 14 14 05" src="https://user-images.githubusercontent.com/929743/152786166-4c420f48-3b8a-4f05-85bc-12ba91225e1a.png">

2022-02-07 12:32 UTC, gbraad approved these changes

2022-02-07 12:33 UTC, gbraad commented on frontend/src/components/about/AboutWindow.tsx
> +              <Button variant="link" className={styles.docButton} icon={<ExternalLinkSquareAltIcon />} iconPosition="right" component="a" onClick={this.openDocumentationLink} target="_blank">
center align looks weird, like it is a button to press

2022-02-07 12:34 UTC, merged