add telemetry module to send data to segment
crc-org/tray-electron pull request #23
Opened 2021-12-14 05:17 UTC by anjannath

2021-12-15 12:51 UTC, cfergeau commented on telemetry.js
> +            this.userIdHash = idHash
Is this going to be persisted to disk without an explicit call to `writeUserIdHash`? I would remove the generation of the user id hash from `getUserIdHash` and only return "" when the user id hash can't be read. Then you can have an explicit call to `writeUserIdHash` here.

Side-node, `getUserIdHash` VS `getUserID` (ID capitalization), and maybe `writeUserIdHash` would be a better name than `writeNewHash`.

2021-12-15 12:54 UTC, cfergeau commented on telemetry.js
> +        if (!this.telemetryEnabled) {
I usually try to avoid comments which are just paraphrasing easy to read code, especially if they are repeated in multiple places. If this needs to be explicitly described, then you are missing a small helper with good naming to make it obvious what is happening. If the code is easy enough to read (and I think it is here, even if the negation makes this slightly harder to parse), then the comment is not useful.

2021-12-16 06:18 UTC, gbraad commented on config.js
> +        let v = this.store.get(key)
```javascript
        return this.store.get(key)
```

2021-12-16 06:20 UTC, gbraad commented on main.js
> +    telemetry.trackError(`Error at main.start(): Backend failure, Backend failed to start: ${err}`)
```javascript
    const msg = `Backend failure, Backend failed to start: ${err}`;
    dialog.showErrorBox(`Backend failure`, msg);
    telemetry.trackError(`Error at main.start(): ${msg}`);
```

2021-12-16 06:21 UTC, gbraad commented on preload.js
> +const Telemetry = require('./telemetry');
I have broken preload in two distinct files for setup and main.
will have to merge this.

2021-12-16 06:23 UTC, gbraad commented on telemetry.js
> +        if (!this.telemetryEnabled) {
This is a pattern I introduced in the time of Minishift and it not a bad trait. Keep doing it.
Every function should be guarded by a entry bailout when conditions aren't met.

2021-12-16 06:26 UTC, gbraad commented on telemetry.js
> +function writeNewHash(identity) {
Unclear naming

2021-12-16 06:27 UTC, gbraad requested changes
As mention in the comments

2021-12-16 07:14 UTC, gbraad commented on preload.js
> +const Telemetry = require('./telemetry');
Please rebase

2021-12-16 07:28 UTC, anjannath commented on telemetry.js
> +function writeNewHash(identity) {
How about `writeNewIdHash` ?

2021-12-16 07:43 UTC, cfergeau commented on telemetry.js
> +        if (!this.telemetryEnabled) {
I'm only objecting to the redundant comment here. The helper suggestion was something more generic which is useful in other situations, but I agree it's not needed here.

2021-12-16 08:04 UTC, anjannath commented on preload.js
> +const Telemetry = require('./telemetry');
@gbraad i added the `telemetry` object to `preload-main.js` for now

2021-12-16 12:04 UTC, anjannath commented on telemetry.js
> +        if (!this.telemetryEnabled) {
@cfergeau will remove the comments, its pretty simple, it was added for me to remember to add the check here

2021-12-16 13:00 UTC, anjannath commented on telemetry.js
> +function writeNewHash(identity) {
i see this is what @cfergeau also suggested, so going with `writeUserIdHash`

2021-12-16 14:40 UTC, anjannath commented
> Add telemetry related function to preload-main.js
the preload script has a limitation that it cannot
require local js files, so we cannot directly require
the telemetry.js file in preload-main.js
instead we use ipcMain and ipcRenderer to expose the
telemetry related functions via the preload script

this limitation is gone with the latest electron, any 16.0+ version, will update ours also to 16

2021-12-17 10:59 UTC, merged