open links in new window and ask for confirmation before closing on-boarding wizard
crc-org/tray-electron pull request #54
Opened 2022-01-04 07:51 UTC by anjannath

- show the on-boarding wizard when necessary (bundle is not available)
- make the links in the setup wizard open in a new window
- ask for confirmation before closing the on-boarding wizard

2022-01-04 08:58 UTC, gbraad commented on frontend/src/components/SetupWindow.jsx
> +                    <Button variant={ButtonVariant.link} component="a" href="https://crc.dev" target="_blank" rel="noreferrer">Visit Getting started Guide</Button>
I am actually not sure if we should do this. This opens in an Electron Window. The one for the pull-secret we can possibly automate, like performing the actions for you, or monitoring the clipboard.

I think this one should act the same as the "Open Console" and should there invoke a window.api call that the main process handles.

2022-01-04 08:59 UTC, gbraad requested changes
use Shell to open the links, as that will use the user's preferred browser instead.

2022-01-04 09:00 UTC, gbraad commented on package.json
> +    "start:dev": "concurrently \"cd frontend && npm start\" \"electron .\""
he he he , yeah... the frontend takes longer to start.

2022-01-04 09:02 UTC, anjannath commented on frontend/src/components/SetupWindow.jsx
> +                    <Button variant={ButtonVariant.link} component="a" href="https://crc.dev" target="_blank" rel="noreferrer">Visit Getting started Guide</Button>
agreed, that was my also my initial thought, will update it

2022-01-04 09:53 UTC, gbraad commented on frontend/src/components/SetupWindow.jsx
> +                    <Button variant={ButtonVariant.link} component="a" href="https://crc.dev" target="_blank" rel="noreferrer">Visit Getting started Guide</Button>
Eventually the menu and wizard will show Preset specific options and links, provided by a configuration. This is for later development, but would likely also clean up some code.

2022-01-05 05:56 UTC, anjannath commented on frontend/src/components/SetupWindow.jsx
> +                    <Button variant={ButtonVariant.link} component="a" href="https://crc.dev" target="_blank" rel="noreferrer">Visit Getting started Guide</Button>
updated to use `shell.openExternal`

2022-01-06 07:40 UTC, merged