Small fixes
crc-org/tray-electron pull request #7
Opened 2021-09-01 07:03 UTC by anjannath

This PR does the following things:
- Only hide the dock when running on macOS
- Open the context menu when left clicking on the tray icon (existing behavior with the trays)

2021-09-01 07:46 UTC, gbraad requested changes

2021-09-01 07:46 UTC, gbraad commented on main.js
> +if (os.platform() === "darwin")
Can we define something like: 


```js
var platform = os.platform() // or process.platform; not sure which is better or 'standard' in use
var isWin = (platform === "win32");
var isMac = (platform === "darwin");
```

which makes the change:

```js
if (isMac)
```

2021-09-01 07:48 UTC, gbraad requested changes

2021-09-01 07:48 UTC, gbraad commented on main.js
> +  tray.on('click', () => { tray.popUpContextMenu() });
```js
tray.on('click', () => {
    tray.popUpContextMenu()
});
```

consider indents

2021-09-02 06:50 UTC, anjannath commented on main.js
> +if (os.platform() === "darwin")
I went with `var isMac = (os.platform() === "darwin")` this way we get the readable `if(isMac)` and also avoid one extra variable

2021-09-02 06:51 UTC, anjannath commented on main.js
> +  tray.on('click', () => { tray.popUpContextMenu() });
Done

2021-09-08 05:02 UTC, gbraad commented
@anjannath change title of commit to mention "Fixes #6" ?

2021-09-08 05:49 UTC, gbraad requested changes

2021-09-08 05:49 UTC, gbraad commented on main.js
> +if (isMac)
Please use `{`, as if there is an issue, JavaScript will perform `;` insertion to fix it, which would lead to the check not working and always performing the hide.

2021-09-08 06:05 UTC, gbraad approved these changes

2021-09-08 06:06 UTC, merged